name: Latest Medium Posts

on:
  schedule:
    - cron: '0 */6 * * *' # Her 6 saatte bir güncellenir
  workflow_dispatch:

jobs:
  update-medium-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Medium posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@gokaycan"
          max_post_count: 1
          template: "- [$title]($url)"
