name: Update Medium Posts

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-medium-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@GokayCan"
          max_post_count: 3
          template: |
            [![$title]($thumbnail)]($url)  
            [$title]($url)
